# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from trawler.src.main.proto import trawler_pb2 as src_dot_main_dot_proto_dot_trawler__pb2


class TrawlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Record = channel.unary_unary(
                '/trawler.Trawler/Record',
                request_serializer=src_dot_main_dot_proto_dot_trawler__pb2.RecordRequest.SerializeToString,
                response_deserializer=src_dot_main_dot_proto_dot_trawler__pb2.RecordResponse.FromString,
                )


class TrawlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Record(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrawlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Record': grpc.unary_unary_rpc_method_handler(
                    servicer.Record,
                    request_deserializer=src_dot_main_dot_proto_dot_trawler__pb2.RecordRequest.FromString,
                    response_serializer=src_dot_main_dot_proto_dot_trawler__pb2.RecordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trawler.Trawler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Trawler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Record(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trawler.Trawler/Record',
            src_dot_main_dot_proto_dot_trawler__pb2.RecordRequest.SerializeToString,
            src_dot_main_dot_proto_dot_trawler__pb2.RecordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
